buildVariable: true
category:
- SERIF
familyName: Bhoto Serif Devanagari
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- BhotoSerifDevanagari.glyphspackage
